name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
